# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build -- -d --linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Upload AppImage as artifact
        uses: actions/upload-artifact@v3
        with:
          name: AppImage
          path: release/0.0.0/Accolades-Linux-0.0.0.AppImage

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: AppImage
          path: release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: release/Accolades-Linux-0.0.0.AppImage
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
